version: '3.8'

services:
  users-microservice:
    build:
      context: ./microservices/users
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db

  authors-microservice:
    build:
      context: ./microservices/authors
    ports:
      - "8082:8082"
    depends_on:
      - postgres-db

  categories-microservice:
    build:
      context: ./microservices/categories
    ports:
      - "8083:8083"
    depends_on:
      - postgres-db

  books-microservice:
    build:
      context: ./microservices/books
    ports:
      - "8084:8084"
    depends_on:
      - postgres-db

  borrows-microservice:
    build:
      context: ./microservices/borrows
    ports:
      - "8085:8085"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "54320:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
